name: Hugo Actions  # 名字自取

on:
  push:
    branches:
      - main  # 这里的意思是当 main 分支发生 push 的时候，运行下面的 jobs

jobs:
  deploy: 
    runs-on: ubuntu-latest	        # 在什么环境运行任务
    steps:
      - uses: actions/checkout@v4       # 引用actions/checkout这个action，与所在的github仓库同名
        with:
         submodules: recursive          # Fetch Hugo themes (true OR recursive) 获取submodule主题
         fetch-depth: 0                 # Fetch all history for .GitInfo and .Lastmod
         
      - name: Pull & update submodules recursively
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote
      - name: Commit
        run: |
          git config user.email "weiyanshum@gmail.com"
          git config user.name "shenweiyan"
          git add --all
          git commit -m "Update submodules" || echo "No changes to commit"
          git push

      - name: Setup Hugo	        # 步骤名自取
        uses: peaceiris/actions-hugo@v2	# hugo官方提供的action，用于在任务环境中获取hugo
        with:
          hugo-version: '0.137.0'	# 获取指定版本的hugo

      - name: Build 
        run: hugo         	# 使用 hugo 构建静态网页

      - name: Deploy To Bioit-top                       # 部署至当前仓库的其他分支
        uses: peaceiris/actions-gh-pages@v3             # 一个自动发布github pages的action
        with:
          #external_repository: shenweiyan/WebStack-Demo	# 发布到哪个repo, 不填写则默认发布到当前仓库
          personal_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}	  
          publish_dir: ./public
          publish_branch: gh-pages
          force_orphan: true
         # cname: webstack-demo.weiyan.cc
          full_commit_message: ${{ github.event.head_commit.message }}
